# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

fos_ck_editor:
    js_path: 'vendor/ckeditor/ckeditor.index.js'
    default_config: "base_config"
    configs:
        base_config:
            toolbar: "full"
            removePlugins: 'wsc'
            stylesSet: "xgsb_styles"
    styles:
        xgsb_styles:
            - { name: "Image responsive", element: "img", attributes: { class: "img-fluid" } }
            - { name: "Baseline", element: "h1", attributes: { class: "baseline" } }
            - { name: "Titre module", element: "h3", attributes: { class: "titre-module" } }
            - { name: "Sous titre module", element: "h4", attributes: { class: "sous-titre-module" } }
            - { name: "Centré", element: [ "h1", "h2", "h3", "p", "a" ], attributes: { class: "text-center" } }
            - { name: "liste stylisé", element: "ul", attributes: { class: "list-group list-group-flush" } }
            - { name: "Element liste stylisé", element: "li", attributes: { class: "list-group-item" } }
            - { name: "Bouton info", element: "a", attributes: { class: "btn btn-info px-2" } }
            - { name: "Bouton primaire", element: "a", attributes: { class: "btn btn-primary px-2" } }
            - { name: "Bouton secondaire", element: "a", attributes: { class: "btn btn-secondary px-2" } }
twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'