twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_4_horizontal_layout.html.twig', '@FOSCKEditor/Form/ckeditor_widget.html.twig', 'xgsb/form/customfields.html.twig']

when@test:
    twig:
        strict_variables: true
